administradores/urls.py
from django.urls import path
from . import views

app_name = "administradores"
urlpatterns = [
     #path recicladoras
    path("", views.index, name="index"),
    path("recicladoras/aprobar/", views.aprobar_recicladoras, name="aprobar_recicladoras"),
    path('administradores/recicladoras/', views.ver_recicladoras, name='ver_recicladoras'),
    # path('recicladoras/crear/', views.recicladora_crear, name='recicladora_crear'),
    path('recicladoras/editar/<int:pk>/', views.recicladora_editar, name='recicladora_editar'),
    path('recicladoras/eliminar/<int:pk>/', views.recicladora_eliminar, name='recicladora_eliminar'),

    path('usuarios/', views.listar_usuarios, name='listar_usuarios'),
    path('usuarios/editar/<int:id_usuario>/', views.editar_usuario, name='editar_usuario'),
    path('usuarios/eliminar/<int:id_usuario>/', views.eliminar_usuario, name='eliminar_usuario'),

    # path('tipomaterial/', views.tipo_material_list, name='tipomaterial_list'),
    path('tipomaterial/', views.tipo_material_list, name='tipomaterial_list'),
    path('tipomaterial/registro/', views.tipo_material_registro, name='tipomaterial_registro'),
    path('tipomaterial/<int:pk>/update/', views.tipo_material_actualizar, name='tipomaterial_actualizar'),
    path('tipomaterial/<int:pk>/delete/', views.tipo_material_delete, name='tipomaterial_delete'),

    #path contenidos educativos 
    path('contenido/', views.contenido_educativo_admin, name='contenido_admin'),
    path('contenido/nuevo/', views.contenido_crear, name='contenido_crear'),
    path('contenido/<int:pk>/editar/', views.contenido_editar, name='contenido_editar'),
    path('contenido/<int:pk>/borrar/', views.contenido_borrar, name='contenido_borrar'),

    #retos y recompensas
    path('RetosYRecompensas/', views.RetosYRecompensas, name='RetosYRecompensas'),
    path('agregar_reto/', views.agregar_reto, name='agregar_reto'),  
    path('agregar_recompensa/', views.agregar_recompensa, name='agregar_recompensa'),


    #respaldos
    path('backup/', views.backup, name='backup'),
    path('restaurar-bd/', views.restaurar_toda_db, name='restaurar_bd'),
    path('backupscreen/', views.backupscreen, name='backupscreen'),
    path('restaurar-tabla-archivo/', views.backup_tabla_especif, name='restaurar_tabla_archivo'),
    path('administradores/restaurar-tabla-predefinida/', views.restaurar_tabla, name='restaurar_tabla_especifica'),
    path('descargar-tabla-csv/', views.descargar_tabla_csv, name='descargar_tabla_csv'),


]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("usuarios.urls")),
    path("recicladoras/", include("recicladoras.urls")),
    path("administradores/", include("administradores.urls")),
    path("admin/", admin.site.urls),
    path('usuarios/', include('usuarios.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recicladoras/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

app_name = "recicladoras"
urlpatterns = [
    path("", views.index, name="index"),
    path("entregas/", views.confirmar_entregas, name="confirmar_entregas"),
    path('entregas/get-materiales/<int:punto_id>/', views.get_materiales_aceptados, name='get_materiales'),
    path("agregar_punto/", views.agregar_punto, name="agregar_punto"),
    # path('tipomaterial/', views.tipo_material_list, name='tipomaterial_list'),
    # path('tipomaterial/', views.tipo_material_list, name='tipomaterial_list'),
    # path('tipomaterial/registro/', views.tipo_material_registro, name='tipomaterial_registro'),
    # path('tipomaterial/<int:pk>/update/', views.tipo_material_actualizar, name='tipomaterial_actualizar'),
    # path('tipomaterial/<int:pk>/delete/', views.tipo_material_delete, name='tipomaterial_delete'),
    # path('clasificacion', views.clasificacion, name='clasificacion_materiales'),

    path('solicitar/', views.solicitar_recicladora, name='solicitar_recicladora'),
    path('verpuntosreciclaje/',views.verpuntosreciclaje,name='verpuntosreciclaje'),


]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path

from . import views
from recicladoras import views as recicladoras_views


app_name = "usuarios"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("info/", views.info, name="info"),
    path("perfil/", views.perfil_usuario, name="perfil_usuario"),
    path("ranking/", views.ranking_usuarios, name="ranking_usuarios"),
    path('contenido-educativo/', views.contenido_educativo, name='contenido_educativo'),
    path('Entregas/', views.lista_entregas, name='lista_entregas'),
    path('Entregas/<int:clave>/', views.confirmar_entrega, name='confirmar_entrega'),
    path("registro/", views.usuariosregistro, name="registro"),
    # path('mapa/', views.mapa_google, name='mapa_puntos'),
    path('clasificacion',views.clasificacion, name='clasificacion_materiales'),
    path('recicladoras/<int:id_punto>/', views.detalle_punto_reciclaje, name='punto_detalle'),
    path('mostrarentregas/', views.mostrarentregas, name='mostrarentregas'),
    
    path('api/recicladoras-materiales/', views.vista_json_recicladoras_con_materiales, name='api_recicladoras_materiales'),
    path('recicladoras-materiales/', views.vista_html_recicladoras_con_materiales, name='html_recicladoras_materiales'),
    path('recicladoras/<int:id_punto>/', views.detalle_punto_reciclaje, name='punto_detalle'),
    path('recicladoras/crear/', views.recicladora_crear, name='recicladora_crear'),

    path('RetosYRecompensas/', views.RetosYRecompensas, name='RetosYRecompensas'),

    path('publicaciones/', views.publicaciones, name='publicaciones'),
    path('crear_comentario/', views.crear_comentario, name='crear_comentario'),
    path('crear_publicacion/',views.crear_publicacion,name='crear_publicacion')
    

]

administradores/models.py
from django.db import models

# Create your models here.

core/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from django.core.exceptions import ValidationError
from django.utils import timezone


class ContenidoEducativo(models.Model):
    codigo = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=25, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    id_usuario_ce = models.ForeignKey('Usuarios', models.SET_NULL, db_column='id_usuario_ce', blank=True, null=True)
    # son campos para cargar media
    imagen = models.ImageField(upload_to='contenido/imagenes/', blank=True, null=True)
    videos= models.URLField(blank=True, null=True)
    video_local = models.FileField(upload_to='contenido/videos/', blank=True, null=True)

    def clean(self):
        super().clean()
        if not (self.imagen or self.videos or self.video_local):
            raise ValidationError("Debe subir al menos una imagen, un video local o un enlace de video.")



    class Meta:
        managed = False
        db_table = 'contenido_educativo'


class EntregaMaterialReciclado(models.Model):
    id_entrega_material = models.AutoField(primary_key=True)
    id_entrega = models.ForeignKey('Entregas', models.DO_NOTHING, db_column='id_entrega', blank=True, null=True)
    id_material = models.ForeignKey('MaterialReciclable', models.DO_NOTHING, db_column='id_material', blank=True, null=True)
    cantidad = models.IntegerField(blank=True, null=True)
    condiciones_entrega = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'entrega_material_reciclado'


class Entregas(models.Model):
    id_entrega = models.AutoField(primary_key=True)
    fecha_entrega = models.DateTimeField(blank=True, null=True)
    id_usuario_e = models.ForeignKey('Usuarios', models.SET_NULL, db_column='id_usuario_e', blank=True, null=True)
    punto_entrega = models.ForeignKey('PuntosReciclaje', models.DO_NOTHING, db_column='punto_entrega', blank=True, null=True)
    confirmada = models.BooleanField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'entregas'


class MaterialReciclable(models.Model):
    id_material = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    tipo_reciclaje = models.ForeignKey('TipoMaterialReciclable', models.DO_NOTHING, db_column='tipo_reciclaje', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'material_reciclable'


class Publicaciones(models.Model):
    clave_publicacion = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30, blank=True, null=True)
    contenido = models.TextField(blank=True, null=True)
    id_usuario_p = models.ForeignKey('Usuarios', models.SET_NULL, db_column='id_usuario_p', blank=True, null=True)
    fecha_publicacion = models.DateTimeField(default=timezone.now)  # <-- Nuevo campo


    class Meta:
        managed = False
        db_table = 'publicaciones'


class PuntosReciclaje(models.Model):
    id_punto = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    ubicacion = models.TextField(blank=True, null=True)
    telefono = models.CharField(max_length=50, blank=True, null=True)
    horario_entrada = models.TimeField(blank=True, null=True)
    horario_salida = models.TimeField(blank=True, null=True)
    id_recicladora = models.ForeignKey('Recicladoras', models.DO_NOTHING, db_column='id_recicladora', blank=True, null=True)
    ciudad = models.CharField(max_length=50, blank=True, null=True)
    #se usaran para que funcione google maps 
    extras = models.TextField(blank=True, null=True)
    latitud = models.FloatField(blank=True, null=True)
    longitud = models.FloatField(blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    class Meta:
        managed = False
        db_table = 'puntos_reciclaje'


class Recicladoras(models.Model):
    codigo_recicladora = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    propietario = models.ForeignKey('Usuarios', models.SET_NULL, db_column='propietario', blank=True, null=True)
    calle = models.CharField(max_length=50, blank=True, null=True)
    codigo_postal = models.IntegerField(blank=True, null=True)
    colonia = models.CharField(max_length=50, blank=True, null=True)
    numero_int = models.IntegerField(blank=True, null=True)
    ciudad = models.CharField(max_length=30, blank=True, null=True)
    numero_telefonico = models.CharField(max_length=20, blank=True, null=True)
    aprobada = models.BooleanField(blank=True, null=True)
    detalles = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'recicladoras'


class Recompensas(models.Model):
    codigo = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=30, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    puntos_requeridos = models.IntegerField(blank=True, null=True)
    clave_reto = models.ForeignKey('Retos', models.DO_NOTHING, db_column='clave_reto', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'recompensas'


class Retos(models.Model):
    codigo = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    puntos_obtenidos = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'retos'


class Roles(models.Model):
    id_rol = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=20, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'roles'


class TipoMaterialReciclable(models.Model):
    id_tmr  = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=40, blank=True, null=True)
    descripcion = models.TextField(blank=True, null=True)
    tiempo_descomposicion = models.TextField(blank=True, null=True)
    imagen = models.ImageField(upload_to='clasificacion/', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'tipo_material_reciclable'


class Usuarios(models.Model):
    id_usuario = models.AutoField(primary_key=True)
    nombre = models.CharField(max_length=50, blank=True, null=True)
    ap_paterno = models.CharField(max_length=25, blank=True, null=True)
    ap_materno = models.CharField(max_length=25, blank=True, null=True)
    correo = models.CharField(max_length=100, blank=True, null=True)
    contrasena = models.CharField(max_length=20, blank=True, null=True)
    fecha_nacimiento = models.DateField(blank=True, null=True)
    fecha_registro = models.DateTimeField(blank=True, null=True)
    total_recompensas = models.IntegerField(blank=True, null=True)
    puntos = models.IntegerField(blank=True, null=True)
    id_rol = models.ForeignKey(Roles, models.DO_NOTHING, db_column='id_rol', blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuarios'


class UsuariosRecompensas(models.Model):
    pk = models.CompositePrimaryKey('id_usuario', 'id_recompensa')
    id_usuario = models.ForeignKey(Usuarios, models.DO_NOTHING, db_column='id_usuario')
    id_recompensa = models.ForeignKey(Recompensas, models.DO_NOTHING, db_column='id_recompensa')
    fecha_canjeo = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuarios_recompensas'


class UsuariosRetos(models.Model):
    pk = models.CompositePrimaryKey('id_usuario', 'id_reto')
    id_usuario = models.ForeignKey(Usuarios, models.DO_NOTHING, db_column='id_usuario')
    id_reto = models.ForeignKey(Retos, models.DO_NOTHING, db_column='id_reto')
    fecha_inicio = models.DateField(blank=True, null=True)
    fecha_fin = models.DateField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'usuarios_retos'

class SolicitudRegistro(models.Model):
    nombre_establecimiento = models.CharField(max_length=100)
    ubicacion = models.TextField()
    horarios_atencion = models.CharField(max_length=100)
    telefono_contacto = models.CharField(max_length=20)
    materiales_aceptados = models.TextField()
    aprobado = models.BooleanField(default=False)
    
class MaterialAceptado(models.Model):
    id_ma = models.AutoField(primary_key=True)
    id_punto = models.ForeignKey('PuntosReciclaje', on_delete=models.CASCADE, db_column='id_punto')
    id_tipo_material = models.ForeignKey('TipoMaterialReciclable', on_delete=models.CASCADE, db_column='id_tipo_material')

    class Meta:
        managed = False
        db_table = 'material_aceptado'


###########################################
class Comentarios(models.Model):
    id = models.AutoField(primary_key=True)  
    contenido = models.TextField()
    fecha_creacion = models.DateTimeField(blank=True, null=True)
    id_publicacion = models.ForeignKey('Publicaciones', models.DO_NOTHING, db_column='id_publicacion')
    id_usuario = models.ForeignKey('Usuarios', models.DO_NOTHING, db_column='id_usuario')

    class Meta:
        managed = False
        db_table = 'comentarios'

recicladoras/forms.py
# recicladoras/forms.py
import os
from django import forms
# from core.models import TipoMaterialReciclable
from core.models import Recicladoras

# class SolicitudRecicladoraForm(forms.ModelForm):
#     class Meta:
#         model = SolicitudRegistro
#         fields = '__all__'
#         exclude = ['aprobado']  # ocultamos esto para que solo el admin lo modifique
class SolicitudRecicladoraForm(forms.ModelForm):
    class Meta:
        model = Recicladoras
        fields = [
            'nombre',
            'propietario',
            'calle',
            'codigo_postal',
            'colonia',
            'numero_int',
            'ciudad',
            'numero_telefonico'
        ]
# class TipoMaterialReciclableForm(forms.ModelForm):
#     class Meta:
#         model = TipoMaterialReciclable
#         fields = ['nombre', 'descripcion', 'tiempo_descomposicion', 'imagen']

#     def __init__(self, *args, **kwargs):
#         is_update = kwargs.pop('is_update', False)
#         super().__init__(*args, **kwargs)
#         for field in self.fields.values():
#             field.widget.attrs.update({'class': 'form-control'})
#         if is_update:
#             self.fields['imagen'].required = False
#         else:
#             self.fields['imagen'].required = True

#     def clean_imagen(self):
#         imagen = self.cleaned_data.get('imagen')
#         if imagen:
#             ext = os.path.splitext(imagen.name)[1].lower()
#             if ext not in ['.jpg', '.jpeg', '.png']:
#                 raise forms.ValidationError("Sólo se permiten imágenes JPG, JPEG o PNG.")
#             if imagen.size > 10 * 1024 * 1024:
#                 raise forms.ValidationError("La imagen no debe superar los 10MB.")
#         return imagen

administradores/templates/administradores/FormReto.html
{% extends "administradores/base.html" %}
{% block title %}Nuevo Reto{% endblock %}

{% block content %}
<div class="form-container">
 <h2>Agregar Nuevo Reto</h2>
 <form method="POST" novalidate id="form-reto">
 {% csrf_token %}

    <div class="form-group">
      <label for="id_titulo">Título</label>
      {{ form.titulo }}
      <div class="error-msg" id="error-titulo"></div>
      {% if form.titulo.errors %}
        <div class="error-msg">{{ form.titulo.errors }}</div>
      {% endif %}
    </div>

    <div class="form-group">
      <label for="id_descripcion">Descripción</label>
      {{ form.descripcion }}
      {% if form.descripcion.errors %}
        <div class="error-msg">{{ form.descripcion.errors }}</div>
      {% endif %}
    </div>

        <div class="form-group">
      <label for="id_puntos_obtenidos">Puntos Obtenidos</label>
      <input type="number" id="id_puntos_obtenidos" name="puntos_obtenidos" required min="0" class="form-input">
    </div>

    <div class="form-actions">
      <button type="submit" class="btn btn-primary">Guardar</button>
      <a href="{% url 'administradores:RetosYRecompensas' %}" class="btn btn-secondary">Cancelar</a>
    </div>
  </form>
</div>

<style>
  /* Agrega estilos para el nuevo input number si es necesario */
  .form-input {
    width: 100%;
    padding: 10px 14px;
    border: 1.8px solid #ccc;
    border-radius: 8px;
    font-size: 1rem;
    transition: border-color 0.3s ease;
    font-family: inherit;
  }
</style>
<script>
  // El script JS no necesita cambios
</script>
{% endblock %}

administradores/templates/administradores/base.html
<!-- Arista Pérez Graciela -->
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'css/style2.css' %}">
	<title>{% block title %}Ecoguía - Panel de Administrador{% endblock %}</title>
</head>
<body>
	<!-- SIDEBAR -->
	<section id="sidebar">
		<a  href="{% url 'administradores:index' %}"  class="brand">
			<i class='bx bxs-leaf'></i>
			<span class="text">EcoGuía</span>
		</a>
		<ul class="side-menu top">
			<li class="{% if request.path == '/administradores/' %}active{% endif %}">
				<a href="{% url 'administradores:index' %}">
					<i class='bx bxs-dashboard'></i><span class="text">Panel de Control</span>
				</a>
			</li>

			<li class="{% if request.resolver_match.url_name == 'aprobar_recicladoras' %}active{% endif %}">
				<a href="{% url 'administradores:aprobar_recicladoras' %}">
					<i class='bx bxs-check-square'></i><span class="text">Solicitud de Recicladoras</span>
				</a>
			</li>
			
			<li class="{% if request.resolver_match.url_name == 'listar_usuarios' %}active{% endif %}">
				<a href="{% url 'administradores:listar_usuarios' %}">
					<i class='bx bxs-user-detail'></i><span class="text">Gestion de usuarios</span>
				</a>
			</li>

			<li class="{% if request.resolver_match.url_name == 'contenido_admin' %}active{% endif %}">
				<a href="{% url 'administradores:contenido_admin' %}">
					<i class='bx bxs-factory'></i><span class="text">Contenido educativo</span>
				</a>
			</li>

			<li class="{% if request.resolver_match.url_name == 'ver_recicladoras' %}active{% endif %}">
				<a href="{% url 'administradores:ver_recicladoras' %}">
					<i class='bx bxs-factory'></i><span class="text">Recicladoras</span>
				</a>
			</li>
			<li class="{% if request.resolver_match.url_name == 'tipomaterial_list' %}active{% endif %}">
				<a href="{% url 'administradores:tipomaterial_list' %}">
					<i class='bx bx-recycle'></i><span class="text">Materiales reciclables</span>
				</a>
			</li>
			<li class="{% if request.resolver_match.url_name == 'RetosYRecompensas' %}active{% endif %}">
				<a href="{% url 'administradores:RetosYRecompensas' %}">
					<i class='bx bx-recycle'></i><span class="text">Retos y recompensas</span>
				</a>
			</li>
			<li class="{% if request.resolver_match.url_name == 'backupscreen' %}active{% endif %}">
				<a href="{% url 'administradores:backupscreen' %}">
					<i class='bx bxs-user-minus'></i><span class="text">Respaldar datos</span>
				</a>
			</li>
		</ul>
		<ul class="side-menu">
			<li><a href="{% url 'usuarios:logout' %}" class="logout"><i class='bx bxs-log-out-circle'></i><span class="text">Cerrar sesión</span></a></li>
		</ul>
	</section>
	<!-- FIN SIDEBAR -->

	<!-- CONTENIDO -->
	<section id="content">
		<!-- NAVBAR -->
		<nav>
			<!-- <i class="bx bx-menu"></i> -->
			<a href="#" class="nav-link"></a>
			<form action="#">
				<!-- <div class="form-input">
					<input type="search" placeholder="Buscar...">
					<button type="submit" class="search-btn"><i class='bx bx-search'></i></button>
				</div> -->
			</form>
			<input type="checkbox" id="switch-mode" hidden>
			<label for="switch-mode" class="switch-mode"></label>
			<!-- <a href="#" class="notification">
				<i class='bx bxs-bell'></i>
				<span class="num">3</span>
			</a> -->
			<a href="#" class="profile">
				<span><h3>{{ request.user.nombre }}</h3></span>
			</a>
		</nav>
		<!-- FIN NAVBAR -->

		<main>
			{% block content %}
			<!-- Aquí va el contenido dinámico -->
			{% endblock %}
		</main>
	</section>

	<script src="{% static 'js/script.js' %}"></script>
</body>
</html>

administradores/templates/administradores/editar_usuario.html
{% extends "administradores/base.html" %}
{% load widget_tweaks %}


{% block title %}Usuarios{% endblock %}

{% block content %}
<div class="head-title">
  <div class="left">
    <h1>Editar Usuario: {{ usuario.nombre }}</h1>
    <ul class="breadcrumb">
      <li><a  href="{% url 'administradores:index' %}" >Administrador</a></li>
      <li><i class='bx bx-chevron-right'></i></li>
      <li><a class=""  href="{% url 'administradores:index' %}" >Usuarios</a></li>
      <li><i class='bx bx-chevron-right'></i></li>
      <li><a class="active"  href="{% url 'administradores:index' %}" >Editar</a></li>
    </ul>
  </div>
</div>

<div class="container mt-4">
    <form method="post" class="row g-3">
        {% csrf_token %}

        <div class="col-md-6">
            <label for="id_nombre" class="form-label">Nombre</label>
            {{ form.nombre|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_ap_paterno" class="form-label">Apellido paterno</label>
            {{ form.ap_paterno|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_ap_materno" class="form-label">Apellido materno</label>
            {{ form.ap_materno|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_correo" class="form-label">Correo</label>
            {{ form.correo|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_contrasena" class="form-label">Contraseña</label>
            {{ form.contrasena|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_fecha_nacimiento" class="form-label">Fecha de nacimiento</label>
            {{ form.fecha_nacimiento|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_fecha_registro" class="form-label">Fecha de registro</label>
            {{ form.fecha_registro|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_total_recompensas" class="form-label">Total recompensas</label>
            {{ form.total_recompensas|add_class:"form-control" }}
        </div>

        <div class="col-md-6">
            <label for="id_id_rol" class="form-label">Rol</label>
            {{ form.id_rol|add_class:"form-select" }}
        </div>

        <div class="col-12 text-end">
            <button class="btn btn-download" type="submit" style="background-color: #67AE6E; color:#ffff; border-radius: 30px">
                <span class="text">Guardar cambios</span>
            </button>
            <a href="{% url 'administradores:listar_usuarios' %}" class="btn btn-secondary" style="border-radius: 30px">Cancelar</a>
        </div>
    </form>
</div>
{% endblock %}

administradores/templates/administradores/recicladoras_confirm_delete.html
{% extends 'administradores/base.html' %}
{% load static %}

{% block content %}
<!-- Manejado por America Garcia Lara
 Cuadro de mensaje para permitir seguir con la accion de eliminar registro de RECICLADORAS -->
<div class="container mt-4">
    <h2>Confirmar eliminación</h2>
    <p>¿Estás seguro que deseas eliminar la recicladora <strong>{{ recicladora.nombre }}</strong>?, se eliminara permanentemente</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'administradores:ver_recicladoras' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}