project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("usuarios.urls")),
    path("recicladoras/", include("recicladoras.urls")),
    path("administradores/", include("administradores.urls")),
    path("admin/", admin.site.urls),
    path('usuarios/', include('usuarios.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.urls import path

from . import views
from recicladoras import views as recicladoras_views


app_name = "usuarios"
urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("info/", views.info, name="info"),
    path("perfil/", views.perfil_usuario, name="perfil_usuario"),
    path("ranking/", views.ranking_usuarios, name="ranking_usuarios"),
    path('contenido-educativo/', views.contenido_educativo, name='contenido_educativo'),
    path('Entregas/', views.lista_entregas, name='lista_entregas'),
    path('Entregas/<int:clave>/', views.confirmar_entrega, name='confirmar_entrega'),
    path("registro/", views.usuariosregistro, name="registro"),
    # path('mapa/', views.mapa_google, name='mapa_puntos'),
    path('clasificacion',views.clasificacion, name='clasificacion_materiales'),
    path('recicladoras/<int:id_punto>/', views.detalle_punto_reciclaje, name='punto_detalle'),
    path('mostrarentregas/', views.mostrarentregas, name='mostrarentregas'),
    
    path('api/recicladoras-materiales/', views.vista_json_recicladoras_con_materiales, name='api_recicladoras_materiales'),
    path('recicladoras-materiales/', views.vista_html_recicladoras_con_materiales, name='html_recicladoras_materiales'),
    path('recicladoras/<int:id_punto>/', views.detalle_punto_reciclaje, name='punto_detalle'),
    path('recicladoras/crear/', views.recicladora_crear, name='recicladora_crear'),

    path('RetosYRecompensas/', views.RetosYRecompensas, name='RetosYRecompensas'),

    path('publicaciones/', views.publicaciones, name='publicaciones'),
    path('crear_comentario/', views.crear_comentario, name='crear_comentario'),
    path('crear_publicacion/',views.crear_publicacion,name='crear_publicacion')
    

]

usuarios/models.py
from django.db import models

# Create your models here.

usuarios/views.py
from django.http import HttpRequest, HttpResponseForbidden
from django.shortcuts import redirect, render, get_object_or_404
from core.models import Recicladoras, Recompensas, Roles, Usuarios,Entregas
from django.shortcuts import redirect, render
from core.models import Usuarios,Entregas, PuntosReciclaje,ContenidoEducativo,EntregaMaterialReciclado,TipoMaterialReciclable, MaterialAceptado, Publicaciones, Comentarios, Retos
from django.utils.timezone import now
from django.utils import timezone
from django.urls import reverse
from core.auth import login_required
from django.db import connection
from django.http import JsonResponse
# usuarios/views.py

from django.contrib import messages
from django.utils.timezone import now


def index(request):
    return render(request, "usuarios/index.html")

def info(request):
    return render(request, "usuarios/infoecoguia.html")


def login(request: HttpRequest):
    if request.method == "GET":
        return render(request, "usuarios/login.html")

    (email, password) = extract_credentials(request)

    # Si el correo y contrasena son correctos, permite el accesso
    (valid, message, user) = verify_crendentials(email, password)

    if not valid:
        return render(
            request, "usuarios/login.html", {"message": message, "email": email}
        )

    # Guarda el id del usuario en la session
    request.session["user_id"] = user.id_usuario

    # Redirecciona a la vista adecuada segun el tipo de usuario
    return map_user_rol(user)

def logout(request: HttpRequest):
    request.session.flush()
    return redirect('usuarios:login')

@login_required(role="usuario")
# def perfil_usuario(request):
#     usuario = get_object_or_404(Usuarios, pk=request.user.id_usuario)
#     modo_edicion = request.GET.get("editar") == "1"

#     if request.method == 'POST':
#         usuario.nombre = request.POST.get('nombre')
#         usuario.ap_paterno = request.POST.get('ap_paterno')
#         usuario.ap_materno = request.POST.get('ap_materno')
#         usuario.correo = request.POST.get('correo')
#         usuario.contrasena = request.POST.get('contrasena')
#         usuario.fecha_nacimiento = request.POST.get('fecha_nacimiento')
#         usuario.save()
#         return redirect('usuarios:perfil_usuario')

#     return render(request, 'usuarios/perfil.html', {
#         'usuario': usuario,
#         'modo_edicion': modo_edicion
#     })

def perfil_usuario(request):
    usuario = get_object_or_404(Usuarios, pk=request.user.id_usuario)
    modo_edicion = request.GET.get("editar") == "1"

    if request.method == 'POST':
        usuario.nombre = request.POST.get('nombre')
        usuario.ap_paterno = request.POST.get('ap_paterno')
        usuario.ap_materno = request.POST.get('ap_materno')
        usuario.correo = request.POST.get('correo')
        usuario.contrasena = request.POST.get('contrasena')
        usuario.fecha_nacimiento = request.POST.get('fecha_nacimiento')
        usuario.save()
        return redirect('usuarios:perfil_usuario')

    # Obtener recompensas del usuario
    recompensas = Recompensas.objects.filter(
        usuariosrecompensas__id_usuario=usuario.id_usuario
    )

    return render(request, 'usuarios/perfil.html', {
        'usuario': usuario,
        'modo_edicion': modo_edicion,
        'recompensas': recompensas
    })

# En tu archivo: usuarios/views.py

from django.views.decorators.http import require_http_methods


@require_http_methods(["GET", "POST"])
def recicladora_crear(request):
    user_id = request.session.get("user_id")
    errores = {}
    recicladora_data = {}
    
    try:
        reciclador_rol = Roles.objects.get(nombre='Recicladora')
    except Roles.DoesNotExist:
        print("Error: El rol 'Recicladora' no existe.")
        return JsonResponse({'success': False, 'message': 'Configuración de rol inválida'}, status=500)

    propietarios = Usuarios.objects.filter(id_rol=reciclador_rol) 

    if request.method == 'POST':
        nombre = request.POST.get('nombre')
        try:
            propietario_obj = Usuarios.objects.get(id_usuario=user_id) 
        except Usuarios.DoesNotExist:
            errores['propietario'] = 'Usuario no encontrado.'
            propietario_obj = None 

        calle = request.POST.get('calle')
        colonia = request.POST.get('colonia')
        ciudad = request.POST.get('ciudad')
        codigo_postal = request.POST.get('codigo_postal')
        numero_int = request.POST.get('numero_int')
        telefono = request.POST.get('numero_telefonico')
        aprobada = False 
        detalles = request.POST.get('detalles')

        recicladora_data = {
            'nombre': nombre,
            'calle': calle,
            'colonia': colonia,
            'ciudad': ciudad,
            'codigo_postal': codigo_postal,
            'numero_int': numero_int,
            'numero_telefonico': telefono,
            'detalles': detalles,
        }

        if not nombre:
            errores['nombre'] = 'El nombre es obligatorio.'
        if not ciudad:
            errores['ciudad'] = 'La ciudad es obligatoria.'
        if not propietario_obj: 
            errores['propietario'] = 'No se pudo asignar la recicladora al usuario actual.'
        if codigo_postal and (not codigo_postal.isdigit() or len(codigo_postal) != 5):
            errores['codigo_postal'] = 'El código postal debe ser un número de 5 dígitos.'
        if numero_int and not numero_int.isdigit():
            errores['numero_int'] = 'El número interior debe ser un número.'
        if telefono and (not telefono.isdigit() or len(telefono) != 10):
            errores['numero_telefonico'] = 'El número de teléfono debe contener 10 dígitos.'


        if not errores:
            try:
                Recicladoras.objects.create(
                    nombre=nombre,
                    propietario=propietario_obj, 
                    calle=calle,
                    colonia=colonia,
                    ciudad=ciudad,
                    codigo_postal=int(codigo_postal) if codigo_postal else None,
                    numero_int=int(numero_int) if numero_int else None,
                    numero_telefonico=telefono,
                    aprobada=aprobada,
                    detalles=detalles
                )
                return JsonResponse({'success': True, 'message': 'Registro entregado con éxito, los administradores revisarán tu solicitud.'})
            except Exception as e:
                errores['general'] = f'Error al guardar la recicladora: {str(e)}'
                return JsonResponse({'success': False, 'errors': errores}, status=500)
        else:
            return JsonResponse({'success': False, 'errors': errores}, status=400)

    return render(request, 'usuarios/recicladora_form.html', {
        'errores': errores,
        'titulo': 'Registrar Recicladora',
        'propietarios': propietarios, 
        'recicladora': recicladora_data 
    })

# def ranking_usuarios(request):
#     usuarios = Usuarios.objects.filter(puntos__isnull=False).order_by('-puntos')[:50]  # top 50
#     return render(request, 'usuarios/ranking.html', {'usuarios': usuarios})

def ranking_usuarios(request):
    top_usuarios = Usuarios.objects.filter(puntos__isnull=False).order_by('-puntos')[:50]

    usuarios_con_recompensa = []
    for usuario in top_usuarios:
        recompensa_top = (
            Recompensas.objects
            .filter(usuariosrecompensas__id_usuario=usuario.id_usuario)
            .order_by('-puntos_requeridos')
            .first()
        )
        usuarios_con_recompensa.append({
            'usuario': usuario,
            'recompensa': recompensa_top
        })

    return render(request, 'usuarios/ranking.html', {
        'usuarios_con_recompensa': usuarios_con_recompensa
    })


def contenido_educativo(request):
    contenidos = ContenidoEducativo.objects.all()
    for contenido in contenidos:
        if contenido.videos:
         contenido.videos_embed = convertir_a_embed(contenido.videos)
    return render(request, 'usuarios/contenido_educativo.html', {'contenidos': contenidos})
# vista para poder utilizar URLS embebidos para insertarlos
def convertir_a_embed(url):
    # if "watch?v=" in url:
    #     return url.replace("watch?v=", "embed/")
    # return url
    import re

    # Extraer ID del video
    video_id = None

    # Caso watch?v=
    m = re.search(r'v=([^\?&]+)', url)
    if m:
        video_id = m.group(1)
    else:
        # Caso youtu.be/
        m = re.search(r'youtu\.be/([^\?&]+)', url)
        if m:
            video_id = m.group(1)

    if video_id:
        return f'https://www.youtube.com/embed/{video_id}'
    else:
        # Si no se puede extraer ID, retorna la URL original
        return url
    
def lista_entregas(request):
    entregas = Entregas.objects.all()
    return render(request, 'usuarios/lista_entregas.html', {'entregas': entregas})  
def confirmar_entrega(request, clave):
    # Obtenemos la entrega
    entrega = get_object_or_404(Entregas, clave=clave)
    entrega.confirmacion = True  # Marcamos como confirmada
    entrega.save()

    # Asignar recompensa al usuario
    usuario = entrega.usuario

    # Por ejemplo: dar la recompensa por "Primera entrega"
    reto, created = Retos.objects.get_or_create(
        titulo="Primera entrega",
        defaults={
            'descripcion': "¡Felicidades por tu primera entrega!",
            'cant_puntos': 100
        }
    )

    Recompensas.objects.create(usuario=usuario, reto=reto)

    # Sumar puntos al usuario
    if usuario.puntos is None:
        usuario.puntos = 0
    usuario.puntos += reto.cant_puntos
    usuario.save()

    return redirect('usuarios:entregas_confirmadas')

# Utilities, not views
# Dependiendo del rol del usuario, redireccionar al area correspondiente
def map_user_rol(user: Usuarios):
    match user.id_rol.pk:  # type: ignore
        # Admin
        case 1:
            return redirect(preserve_request=True, to="administradores:index")

usuarios/templates/usuarios/partials/footer.html
 {% load static %}
<!-- templates/footer.html -->
<footer class="footer">
    <div class="container">
        <div class="footer-grid">
            <div class="footer-about">
                <h3>Ecoguía</h3>
                <p>Una iniciativa que busca transformar el presente para construir un futuro más verde y responsable con el planeta.</p>
                <div class="social-icons">
                    <a href="#"><i class="fab fa-facebook"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-youtube"></i></a>
                </div>
            </div>
            <div class="footer-links">
                <h4>Páginas</h4>
                <ul>
                    <li><a href="#">Inicio</a></li>
                    <li><a href="#">Puntos de Reciclaje</a></li>
                    <li><a href="#">Educación Ambiental</a></li>
                    <li><a href="#">Contáctanos</a></li>
                </ul>
            </div>
            <div class="footer-links">
                <h4>Páginas Útiles</h4>
                <ul>
                    <li><a href="#">Iniciar Sesión</a></li>
                    <li><a href="#">Registrarse</a></li>
                    <li><a href="#">Registrarse</a></li>
                </ul>
            </div>
            <div class="footer-img">
                <h4>Más imágenes</h4>
                <div class="footerImg-grid">
                    <div class="footerImg-img"><img src="{% static 'assets/istockphoto-2166615363-612x612.jpg' %}" alt=""></div>
                    <div class="footerImg-img"><img src="{% static 'assets/photo-1558583055-d7ac00b1adca.png' %}" alt=""></div>
                    <div class="footerImg-img"><img src="{% static 'assets/photo-1582408921715-18e7806365c1.png' %}" alt=""></div>
                    <div class="footerImg-img"><img src="{% static 'assets/istockphoto-2166615363-612x612.jpg' %}" alt=""></div>
                </div>
            </div>
        </div>
    </div>
</footer>

usuarios/templates/usuarios/partials/header.html
{% load static %}
<header>
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <nav class="navbar">
    <div class="nav-container container">

      <!-- Logo -->
      <a class="logo" href="{% url 'usuarios:index' %}">
        <i class="bi bi-recycle me-2 fs-3" ></i>
        EcoGuía
      </a>

      <!-- Botón hamburguesa móvil -->
      <button class="hamburger" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Menú colapsable -->
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="nav-links">
         <li>
            <a class="{% if request.resolver_match.url_name == 'mostrarentregas' %}active{% endif %}" href="{% url 'usuarios:html_recicladoras_materiales' %}">Puntos de reciclaje</a>
          </li>
          <li>
            <a class="{% if request.resolver_match.url_name == 'contenido_educativo' %}active{% endif %}" href="{% url 'usuarios:contenido_educativo' %}">Contenido Educativo</a>
          </li>
          <li>
            <a class="{% if request.resolver_match.url_name == 'RetosYRecompensas' %}active{% endif %}" href="{% url 'usuarios:RetosYRecompensas' %}">Retos y recompensas</a>
          </li>  
           <li>
            <a class="{% if request.resolver_match.url_name == 'index' %}active{% endif %}" href="{% url 'usuarios:mostrarentregas' %}">Historial de reciclaje</a>
          </li> 
          <li>
              <a class="nav-link active" href="{% url 'usuarios:clasificacion_materiales' %}">Clasificacion de materiales</a>
          </li>
          <li>
            <a class="{% if request.resolver_match.url_name == 'ranking' %}active{% endif %}" href="{% url 'usuarios:ranking_usuarios' %}">Ranking de usuarios</a>
          </li> 
           <li>
            <a class="{% if request.resolver_match.url_name == 'publicaciones' %}active{% endif %}" href="{% url 'usuarios:publicaciones' %}">Reseñas</a>
          </li> 

        </ul>
      </div>

      <!-- Botones de usuario -->
      <div class="user-menu ms-auto">
        {% if request.user %}
          <div class="dropdown">
            <button class="dropdown-toggle btn" id="userDropdown" style="margin-left:50px">
              {{ request.user.nombre }} {{ request.user.ap_paterno }}
            </button>
            <ul class="dropdown-menu" id="dropdownMenu">
              <li><a href="{% url 'usuarios:perfil_usuario' %}">👤 Perfil</a></li>
              <li><hr></li>
              <li><a class="logout" href="{% url 'usuarios:logout' %}">🚪 Cerrar Sesión</a></li>
            </ul>
          </div>
        {% else %}
            <div class="botones-usuario">
              <!-- <a href="{% url 'usuarios:login' %}" class="btn">Iniciar sesión</a> -->
              <!-- <a href="{% url 'usuarios:registro' %}" class="btn btn-outline">Registrarse</a> -->
            </div>
        {% endif %}
      </div>
    </div>
  </nav>
</header>

{% comment %} Para que el dropdown funcione {% endcomment %}
<script>
  document.addEventListener('DOMContentLoaded', function () {
    const toggle = document.getElementById('userToggle');
    const menu = document.getElementById('userDropdown');

    toggle?.addEventListener('click', () => {
      menu.classList.toggle('hidden');
    });

    // Close dropdown on outside click
    document.addEventListener('click', function (e) {
      if (!toggle.contains(e.target) && !menu.contains(e.target)) {
        menu.classList.add('hidden');
      }
    });
  });
</script>
<style>
  .botones-usuario {
  display: flex;
  gap: 10px; /* Espacio entre botones */
  align-items: center;
}
</style>